matrix:
- name: German Markdown Spellcheck
  aspell:
    lang: de
    d: de_CH
  dictionary:
    wordlists:
    - .github/wordlist_de.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra
      - markdown.extensions.meta
      - markdown.extensions.tables
      - markdown.extensions.admonition
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
        # ignore sections marked with nospell
        - open: '<!-- nospell -->'
          close: '<!-- endnospell -->'
  - pyspelling.filters.url:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - 'title'
      - 'alt'
      ignores:
      - code
      - pre
  sources:
  - 'i18n/de/docusaurus-plugin-content-docs/**/*.md'
  default_encoding: utf-8
