matrix:
- name: German Markdown Spellcheck
  aspell:
    lang: de
    d: de_CH
    ignore-case: true
  dictionary:
    wordlists:
    - .github/wordlist_de.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
        # ignore pages marked with nospell
        - open: '{{ NOSPELL }}'
          content: '.*'
          close: '\Z'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra
      - markdown.extensions.meta
      - markdown.extensions.tables
      - markdown.extensions.admonition
  - pyspelling.filters.html:
      comments: false
      attributes:
      - 'title'
      - 'alt'
      ignores:
      - code
      - pre
      - table
      - dd
      - dt
      - a
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
        # Ignore multiline content between fences (fences can have 3 or more back ticks)
        # ```
        # content
        # ```
        - open: '(?s)^(?P<open> *`{3,})$'
          close: '^(?P=open)$'
        # Ignore text between inline back ticks
        - open: '(?P<open>`+)'
          close: '(?P=open)'
        # Ignore admonitions
        - open: '::(tip|warning|info)'
          close: '\n'
        # Ignore links
        - open: '\[([^]]*)\]'
          close: '\([^)]*\)'
        # Ignore HTML/MDX etc. tags
        - open: '<([^>]*)>'
          close: '<\/[^>]*>'
        # Ignore HTML comments
        - open: '<!--'
          close: '-->'
  - pyspelling.filters.url:
  sources:
  - 'i18n/de/docusaurus-plugin-content-docs/**/*.md'
  default_encoding: utf-8
